version: '3.7'

volumes:
  pytest_vyper.egg-info:

services:
  pytest-vyper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/pytest-vyper
      - pytest_vyper.egg-info:/usr/src/pytest-vyper/pytest_vyper.egg-info
    environment:
      PYTHONBREAKPOINT: ipdb.set_trace
